name: Build Android ARM64-v8a

on:
  push:
    branches:
      - main  # Change this to your branch, if needed

jobs:
  android-arm64-v8a-build:
    runs-on: ubuntu-latest
    name: Android ARM64-v8a Build

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Set up Android ND
      - name: Set up Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux-x86_64.zip
          unzip android-ndk-r23b-linux-x86_64.zip -d $HOME/ndk
          echo "export ANDROID_NDK=$HOME/ndk/android-ndk-r23b" >> $GITHUB_ENV

      # Step 3: Set up Android SDK (Optional if not needed for other tasks)
      - name: Set up Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
          echo "export ANDROID_SDK=$HOME/android-sdk" >> $GITHUB_ENV

      # Step 4: Install dependencies (if any are required for your build tools)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip
          pip3 install --upgrade setuptools

      # Step 5: Configure the build with CMake for Android ARM64-v8a
      - name: Configure CMake for Android ARM64-v8a
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_NATIVE_API_LEVEL=21 \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
                -DCMAKE_BUILD_TYPE=Release \
                -DDynamicBinaryInstrument=OFF \
                -DPlugin.SymbolResolver=OFF \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_C_COMPILER=clang \
                -B build_android_arm64_v8a

      # Step 6: Build the project for ARM64-v8a architecture
      - name: Build Android ARM64-v8a
        run: |
          cd build_android_arm64_v8a && make dobby

      # Step 7: Collect build artifacts (e.g., libdobby.a)
      - name: Collect build artifacts
        run: |
          mkdir build_result
          cp build_android_arm64_v8a/libdobby.a build_result/libdobby_arm64_v8a.a

      # Step 8: Upload the build artifacts to GitHub Actions
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android_ARM64-v8a
          path: build_result
