name: Build

on: push

jobs:
  win-build:
    runs-on: windows-latest
    name: Windows Build

    steps:
      - uses: actions/checkout@v3

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Configure CMake
        shell: cmd
        run: |
          cmake -DCMAKE_SYSTEM_PROCESSOR=amd64 -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_BUILD_TYPE=Release -DDynamicBinaryInstrument=OFF -DPlugin.SymbolResolver=OFF -A x64 -B build64
          cmake -DCMAKE_SYSTEM_PROCESSOR=x86 -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_BUILD_TYPE=Release -DDynamicBinaryInstrument=OFF -DPlugin.SymbolResolver=OFF -A Win32 -B build32

      - name: Build x86
        run: |
          msbuild -m -p:Configuration=Release -t:dobby build32/Dobby.sln

      - name: Build x64
        run: |
          msbuild -m -p:Configuration=Release -t:dobby build64/Dobby.sln

      - name: Collect artifacts
        shell: cmd
        run: |
          mkdir build_result
          mkdir build_result\x86
          mkdir build_result\x64
          copy "build32\Release\*" "build_result\x86\"
          copy "build64\Release\*" "build_result\x64\"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: build_result

  linux-build:
    runs-on: ubuntu-latest
    name: Linux Build

    steps:
      - uses: actions/checkout@v3
      
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-multilib g++-multilib libc6-dev-i386

      - name: Configure CMake
        run: |
          cmake -DCMAKE_SYSTEM_PROCESSOR=amd64 -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_BUILD_TYPE=Release -DDynamicBinaryInstrument=OFF -DPlugin.SymbolResolver=OFF -B build64
          cmake -DCMAKE_SYSTEM_PROCESSOR=x86 -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_C_FLAGS="-m32" -DCMAKE_SHARED_LINKER_FLAGS="-m32" -DCMAKE_BUILD_TYPE=Release -DDynamicBinaryInstrument=OFF -DPlugin.SymbolResolver=OFF -B build86
          
      - name: Build x64
        run: |
          cd build64 && make dobby
          
      - name: Build x86
        run: |
          cd build86 && make dobby
          
      - name: Collect artifacts
        run: |
          mkdir build_result
          mkdir build_result/x86
          mkdir build_result/x64
          cp build86/* build_result/x86/
          cp build64/* build_result/x64/
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: build_result

  macos-build:
    runs-on: macos-latest
    name: macOS Build

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: |
          cmake -DCMAKE_SYSTEM_PROCESSOR=amd64 -DCMAKE_SYSTEM_NAME=Darwin -DCMAKE_BUILD_TYPE=Release -DDynamicBinaryInstrument=OFF -DPlugin.SymbolResolver=OFF -B build64
          
      - name: Build x64
        run: |
          cd build64 && make dobby
          
      - name: Collect artifacts
        run: |
          mkdir build_result
          mkdir build_result/x64
          cp build64/* build_result/x64/
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: build_result